### PR TITLE
Camelize properties

### PR DESCRIPTION
**Pull request by luilver**

### CODE REVIEW

**Comment by Craiting** [comment]
It didn't seem to work in my test. I tested by putting a breakpoint in the c# code to view the request after clicking "Launch with previous user". I don't think it works because the data being passed in the request is snake case.

image

**Comment by Craiting** [comment]
Just for testing I added `user_guid` and `user_id` back.
image

**Comment by luilver** [comment]
Try it now and let me know.

**Comment by Craiting** [comment]
Hmm I pulled your changes and I'm still getting null for those fields even with the Json property name

**Pull request merged**
